# Generated by Django 4.1.2 on 2022-10-25 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100)),
                ('imagem', models.CharField(blank=True, max_length=50)),
                ('descricao', models.CharField(db_index=True, max_length=300)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categoria.categoria')),
            ],
            options={
                'db_table': 'loja',
            },
        ),
    ]
