# Generated by Django 4.1.2 on 2022-10-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_loja_data_cadastro_alter_loja_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='descricao',
            field=models.CharField(max_length=300),
        ),
    ]
