# Generated by Django 4.1.2 on 2022-11-22 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_alter_loja_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='cnpj',
            field=models.IntegerField(default='123456789123141', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='loja',
            name='nome',
            field=models.CharField(max_length=13),
        ),
    ]
