# Generated by Django 4.1.2 on 2022-11-22 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_loja_cnpj_alter_loja_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='cnpj',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
