# Generated by Django 4.1.2 on 2022-11-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_loja_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='cnpj',
            field=models.CharField(max_length=14),
        ),
    ]
