# Generated by Django 4.1.2 on 2022-11-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_alter_loja_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='imagem',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
