# Generated by Django 4.1.2 on 2022-11-28 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('loja', '0008_alter_loja_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='produtos', to='categoria.categoria'),
        ),
        migrations.AlterModelTable(
            name='loja',
            table='carrinho',
        ),
    ]
