# Generated by Django 4.1.2 on 2022-11-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_alter_loja_categoria_alter_loja_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loja',
            table='loja',
        ),
    ]
