# Generated by Django 3.1 on 2022-11-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_alter_loja_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
