# Generated by Django 4.1.2 on 2022-11-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
