# Generated by Django 4.1.2 on 2022-10-27 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genero_filme', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100)),
                ('imagem', models.CharField(blank=True, max_length=50)),
                ('descricao', models.CharField(max_length=300)),
                ('data_lancamento', models.DateField()),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='filmes', to='genero_filme.generofilme')),
            ],
            options={
                'db_table': 'filme',
            },
        ),
    ]
